# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_pro_test',
                'doc_host': 'https://Jou0us.github.io',
                'git_url': 'https://github.com/Jou0us/nbdev_pro_test',
                'lib_path': 'nbdev_pro_test'},
  'syms': {'nbdev_pro_test.core': {'nbdev_pro_test.core.foo': ('core.html#foo', 'nbdev_pro_test/core.py')}}}
